data:
  amplitude:
    max: 10
    min: 1
  frequency:
    max: 10
    min: 1
  num_features: 18
  num_samples: 10000
  num_sequence: 25
evaluation:
  tags:
  - train_error_epoch
  - valid_error_epoch
  - lr-Adam
experiment: 0
model:
  batch_size: 64
  hidden_size: 512
  learning_rate: 0.003
  num_epochs: 100
  num_layers: 3
paths:
  results: results
  version: 0
system:
  accelerator: gpu
  num_devices: 1
  num_workers: 19
  strategy: auto
